name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
api-version: 1.20
commands:
  storm:
    description: Comando principal para gestionar tormentas.
    usage: /storm <reset|set|toggle|status> [BaseTime|CurrentTime]
    permission: ${name}.use
permissions:
  ${name}.use:
    description: Permite al jugador usar el comando storm.
    default: op
