name: StormPlugin
description: This plugin is created for the Insomnia
author: ewahv1
main: me.ewahv1.plugin.Main
version: 1.0.0
api-version: 1.20
commands:
  storm:
    description: Comando principal para gestionar tormentas.
    usage: /storm <reset|set|toggle|status|reverse> [BaseTime|CurrentTime]
    permission: StormPlugin.use
permissions:
  StormPlugin.use:
    description: Permite al jugador usar el comando storm.
    default: op
